export const personal = {
  name: "Evie",
  fullName: "Kansinee Khuttiya",
  role: "Computer Engineering Student",
  university: "Assumption University",
  tagline: "Building AI systems with security at the core.",
  about: [
    "I'm a Computer Engineering student at Assumption University with a focus on AI engineering and cybersecurity. I like building intelligent systems — and then figuring out how to break them, before someone else does.",
    "My flagship projects bridge AI and security: NYXUS, a full-stack RAG chatbot with production-grade defenses (prompt-injection scoring, PII redaction, OWASP Top 10 code scanner, audit log), and HORUS, an AI-powered threat intelligence dashboard that pulls live CVE data from NVD and summarizes it in plain Thai/English with Gemini.",
    "Beyond those, I work on classical ML, low-level systems with C/C++ and SYCL, and modern web development with Next.js. I'm currently looking for internships and junior roles in AI Engineering, Security Engineering, or full-stack development.",
  ],
  email: "kansinee.dev@gmail.com",
  github: "https://github.com/evieffvy",
  linkedin: "https://www.linkedin.com/in/evieffvy",
  linktree: "https://linktr.ee/evieffvy",
  languages: [
    { name: "Thai", level: "Native" },
    { name: "English", level: "Fluent" },
    { name: "Mandarin", level: "Learning · HSK 3" },
  ],
};

export type Project = {
  slug: string;
  title: string;
  blurb: string;
  description: string;
  tech: string[];
  repo: string;
  demo?: string;
  highlights?: string[];
  cover?: string;
};

export const featured: Project = {
  slug: "nyxus",
  title: "NYXUS",
  blurb: "Full-stack RAG chatbot with security-first design",
  description:
    "An end-to-end Retrieval-Augmented Generation chatbot built to demonstrate production-grade engineering across full-stack, AI, and applied security. Users can chat with a Gemini-powered assistant grounded in PDF documents they upload, scan code for OWASP Top 10 vulnerabilities, and review every privileged action through an audit log.",
  highlights: [
    "PII redaction across 10+ pattern classes including Luhn-validated credit cards, before any user input reaches the LLM",
    "Weighted prompt-injection scoring across 7 signal classes (instruction override, role hijack, system-prompt leak, jailbreaks, delimiter smuggling)",
    "OWASP Top 10 code scanner using structured-output Gemini prompts with severity-rated findings and fix recommendations",
    "Append-only audit log of every privileged action: auth, conversation CRUD, document upload, chat send, security scan",
    "Hardened HTTP headers, slowapi rate limiting, CORS allowlists, retry/backoff for transient LLM errors",
    "GitHub Actions CI running pytest, tsc, and prisma validate on every push",
  ],
  tech: [
    "Next.js 16",
    "React 19",
    "TypeScript",
    "FastAPI",
    "Python",
    "Postgres",
    "Prisma",
    "NextAuth v5",
    "Google Gemini",
    "Tailwind 4",
    "Vercel",
    "Render",
    "Supabase",
  ],
  repo: "https://github.com/evieffvy/NYXUS",
  demo: "https://nyxus-phi.vercel.app",
  cover: "/projects/chat.png",
};

export const featuredHorus: Project = {
  slug: "horus",
  title: "HORUS",
  blurb: "AI-powered threat intelligence dashboard",
  description:
    "A real-time CVE intelligence dashboard for security analysts. HORUS ingests live vulnerabilities from the NVD REST API, summarizes them in plain Thai/English with Google Gemini, and answers follow-up questions through a streaming bilingual chat assistant — with one-click PDF export for offline triage.",
  highlights: [
    "Live CVE ingestion from the NVD REST API v2.0 with CVSS v3.1 / v3.0 / v2 score normalization and severity-band mapping",
    "Structured Thai-language summaries (affected systems, attacker capabilities, remediation urgency) generated by Gemini 1.5 Flash",
    "Streaming bilingual Thai/English security assistant with active-CVE context injected into the system prompt",
    "Filterable analyst UI — keyword, severity, date range, CVSS score — with paginated CVE table and Recharts severity distribution",
    "One-click PDF export of filtered CVE reports via jsPDF + jspdf-autotable for offline triage and stakeholder sharing",
    "Rate-limit-aware NVD fetching with optional API-key elevation (5 → 50 requests / 30 seconds)",
  ],
  tech: [
    "Next.js 14",
    "React 18",
    "TypeScript",
    "Tailwind CSS",
    "Google Gemini",
    "Recharts",
    "jsPDF",
    "NVD API",
    "Vercel",
  ],
  repo: "https://github.com/evieffvy/HORUS",
  demo: "https://horus-vulnscope.vercel.app",
};

export const projects: Project[] = [
  {
    slug: "sycl",
    title: "SYCL Parallel Computing",
    blurb: "60× GPU speedup on NIST SP 800-22 randomness tests — single codebase, any hardware",
    description:
      "Reimplements the NIST SP 800-22 Monobit and Block Frequency tests as SYCL parallel kernels. A single portable codebase runs on Intel CPU, Intel GPU, NVIDIA GPU, and AMD GPU via SYCL/DPC++ — no CUDA lock-in. Achieves 60× peak GPU speedup over the NIST STS serial baseline at 1 GB input with 32 Gbit/s sustained throughput; P-values match the reference within 1×10⁻⁵.",
    highlights: [
      "60× peak GPU speedup over NIST STS 2.1.2 serial reference at 1 GB input; 32 Gbit/s sustained GPU throughput",
      "Monobit kernel: two-phase parallel reduction with work-group shared memory and sycl::atomic_ref for global accumulation",
      "Block Frequency kernel: two-pass data-parallel design with sycl::reduction accumulating chi-squared in double precision",
      "Cross-architecture portability: Intel CPU, Intel GPU, NVIDIA GPU, and AMD GPU from one SYCL/DPC++ source",
      "P-values verified against NIST STS 2.1.2 within floating-point tolerance (<1×10⁻⁵) across all test vectors",
    ],
    tech: ["C++17", "SYCL / DPC++", "Intel oneAPI", "CMake", "Linux"],
    repo: "https://github.com/evieffvy/sycl_project",
    demo: "https://evieffvy.github.io/sycl_project",
  },
  {
    slug: "ml-coursework",
    title: "ML Coursework",
    blurb: "CNN, PCA, clustering, NLP, and rule mining — classical algorithms from scratch",
    description:
      "Six implementations: 120-class dog breed classification via CNN transfer learning, eigenface recognition with manual PCA (NumPy/OpenCV), binary sentiment analysis (Logistic Regression / Naive Bayes, TF-IDF), Apriori market basket mining, K-Means clustering with elbow + silhouette validation, and ID3 decision tree on Titanic survival.",
    tech: ["Python", "scikit-learn", "TensorFlow/Keras", "NumPy", "OpenCV"],
    repo: "https://github.com/evieffvy",
  },
  {
    slug: "vaultify",
    title: "Vaultify",
    blurb: "Fintech crypto landing page — frontend only",
    description:
      "A crypto custody platform landing page with animated price charts, live market tickers, and glassmorphism UI.",
    tech: ["HTML5", "CSS", "JavaScript"],
    repo: "https://github.com/evieffvy/jjh",
    demo: "https://evieffvy.github.io/jjh",
  },
  {
    slug: "forge",
    title: "Forge",
    blurb: "Developer infrastructure landing page — design system in pure HTML/CSS",
    description:
      "A landing page for a developer infrastructure platform. Built with a full CSS design system — custom properties, responsive grid, accessibility (focus rings, reduced-motion), and a multi-column footer — all in plain HTML/CSS with no framework.",
    tech: ["HTML5", "CSS", "JavaScript"],
    repo: "https://github.com/evieffvy/rerd",
    demo: "https://rerd-xi.vercel.app",
  },
];

export const skills = [
  {
    category: "AI / ML",
    items: [
      "Python",
      "scikit-learn",
      "OpenCV",
      "RAG",
      "LLMs",
      "Embeddings",
      "Vector Search",
      "CNN",
      "Transfer Learning",
      "PCA",
      "K-Means",
      "NLP",
    ],
  },
  {
    category: "Frontend",
    items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion", "Recharts", "jsPDF", "HTML5", "CSS"],
  },
  {
    category: "Backend",
    items: [
      "FastAPI",
      "Python",
      "Node.js",
      "NextAuth",
      "Prisma",
      "Postgres",
      "SQL",
      "REST APIs",
      "OAuth 2.0",
    ],
  },
  {
    category: "Security",
    items: [
      "OWASP Top 10",
      "Prompt Injection",
      "PII Redaction",
      "CVE Analysis",
      "Threat Intelligence",
      "NVD API",
      "Web App Security",
      "Authentication",
      "Rate Limiting",
      "Security Headers",
    ],
  },
  {
    category: "Systems",
    items: ["C", "C++", "SYCL", "Intel oneAPI", "CMake", "Linux", "Bash"],
  },
  {
    category: "Tools",
    items: ["Git", "GitHub Actions", "CI/CD", "Vercel", "Render", "Supabase"],
  },
];

export const education = {
  school: "Assumption University (ABAC)",
  degree: "Bachelor of Engineering · Computer Engineering",
  period: "3rd–4th year",
  location: "Bangkok, Thailand",
  graduation: "Expected Graduation: October 2027",
};
